//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

namespace WcfService
{
    using System;
    using System.Collections.Generic;
    
    [DataContract]
    public partial class Policies
    {
        [DataMember]
        public int ID { get; set; }
        [DataMember]
        public string name { get; set; }
        [DataMember]
        public string description { get; set; }
        [DataMember]
        public string type { get; set; }

        public Policies(int i, string n, string d, string t)
        {
            ID = i;
            name = n;
            description = d;
            type = t;
        }
    }
}
